<!DOCTYPE html>
<html>
<head>
<title>Моя первая страница</title>
</head>
<body>
<h1>Привет Всем!</h1>
<p> Параграф через тег P</p>
<a href="https://mail.ru"> Почта  </a>
<p> пропуск для разделения ссылок на почту и ютубчик</p>
<a href="https://www.youtube.com/watch?v=SKRydSA2bYA&t=427s"
target="blank"> Просто проверка доп ссылки</a>
<h2>Привет всемH2</h2>
<p> Параграф через тег P</p>
<img
src="E:\ImageRespository\black-fox.jpg"
alt="Невозможно загрузить изображение."
width=" 300px"/>
<h2>Я в соцсетях. ШрифтН2</h2>
<ul>
    <li>
    <a href=" https://instagram.com/teramozg/">Instagram</a>
    </li>
    <li>
    <a href=" https://t.me/teramozg/">Telegram</a>
    </li>
</ul>

</body>
</html>
